---
# After Install:
# apt install bridge-utils

# example network-config br_inet on physical interface "enp3s0":
#iface enp3s0 inet manual
#
#auto br_inet
#iface br_inet inet static
#  address 1.2.3.4
#  netmask 255.255.255.0
#  gateway 1.2.3.1
#  up route add -net 1.2.3.0 netmask 255.255.255.0 gw 1.2.3.1 dev br_inet

#  bridge_ports enp3s0
#  bridge_fd 9
#  bridge_hello 2
#  bridge_maxage 12

- name: Ensure that Libvirt is configured
  hosts: all
  roles:
    # - role: stackhpc.libvirt-host
    - role: tcharl.ansible_role_libvirt_host
      libvirt_vm_basedir: "/srv/kvm/images"
      libvirt_vm_isodir: "/srv/kvm/bootCD"

      libvirt_host_pools:
        - name: images
          type: dir
          capacity: 1024
          path: "{{ libvirt_vm_basedir }}"
          mode: 750
          owner: root
          group: libvirt-qemu
        - name: bootCD
          type: dir
          capacity: 1024
          path: "{{ libvirt_vm_isodir }}"
          mode: 750
          owner: root
          group: libvirt-qemu
      libvirt_host_networks:
        - name: br_inet
          mode: bridge
          bridge: br_inet
        - name: br_10g
          mode: bridge
          bridge: br_10g
#        - name: br_inet_nat
#          mode: nat
#          bridge: br_inet
#          domain: example.local
#          ip: 10.240.240.254
#          netmask: 255.255.255.0
#          dhcp_start: 10.240.240.100
#          dhcp_end: 10.240.240.200
  tasks:
  - name: enable autostart on bridge br_inet
    virt_net:
      autostart: yes
      state: active
      name: br_inet
  - name: enable autostart on bridge br_10g
    virt_net:
      autostart: yes
      state: active
      name: br_10g
