---
# configures grub boot loader
# possibly settings a password is interesting too: https://github.com/hudecof/ansible_grub_password

- name: Configure grub (Debian-family)
  ansible.builtin.lineinfile:
    path: "{{ baserole_grub_default_file }}"
    regexp: '^GRUB_CMDLINE_LINUX='
    line: 'GRUB_CMDLINE_LINUX="{{ baserole_grub_commandline }}"'
    backup: true
  notify: Update Grub Config
  when:
    - baserole_grub_commandline is defined
    - ansible_os_family == "Debian"

- name: Configure grub (Redhat-family)
  ansible.builtin.lineinfile:
    path: "{{ baserole_grub_default_file }}"
    regexp: '^GRUB_CMDLINE_LINUX='
    line: 'GRUB_CMDLINE_LINUX="{{ baserole_grub_commandline }}"'
    backup: true
  notify: Update Grub Config
  when:
    - baserole_grub_commandline is defined
    - ansible_os_family == "Redhat"
