---
- name: Template SSHD Config (template)
  ansible.builtin.template:
    src: "{{ baserole_openssh_template_sshd }}"
    dest: "/etc/ssh/sshd_config"
    owner: root
    group: root
    mode: '0644'
    validate: "/usr/sbin/sshd -T -C user=root -C host=localhost -C addr=localhost -f %s"
  notify: Restart SSHD
  when:
    - baserole_openssh_use_template|bool

- name: Template default SSHD Config (template)
  ansible.builtin.template:
    src: "{{ baserole_openssh_template_default }}"
    dest: "/etc/default/ssh"
    backup: true
    owner: root
    group: root
    mode: '0644'
  notify: Restart SSHD
  when:
    - baserole_openssh_sshd_opts is defined
    - baserole_openssh_sshd_opts|length > 0

# needs community.crypto:
- name: Generate SSH host keys (when enabled and/or forced)
  community.crypto.openssh_keypair:
    path: "/etc/ssh/ssh_host_{{ item }}_key"
    type: "{{ item }}"
    force: "{{ baserole_openssh_force_gen_keys | bool }}"
  with_items:
    - "{{ baserole_openssh_key_types }}"
  when:
    - baserole_openssh_gen_keys|bool
  notify: Restart SSHD

- name: Create SSHRC (Skript runs when user logins)
  ansible.builtin.template:
    src: "{{ baserole_openssh_sshrc_template }}"
    dest: /etc/ssh/sshrc
    owner: root
    group: root
    mode: 0755
  when:
    - baserole_openssh_sshrc_enable|bool
