---
- name: Ensure /etc/nginx/sites-enabled/default is absent
  ansible.builtin.file:
    path: '/etc/nginx/sites-enabled/default'
    state: 'absent'
  notify: Restart nginx

- name: Ensure /etc/nginx/sites-available/mattermost is present
  ansible.builtin.template:
    dest: '/etc/nginx/sites-available/mattermost'
    mode: '0644'
    src: '{{ mattermost_nginx_template }}'
  notify: Restart nginx

- name: Enable nginx config via symbolic link
  ansible.builtin.file:
    src: '/etc/nginx/sites-available/mattermost'
    dest: '/etc/nginx/sites-enabled/mattermost'
    state: 'link'
  notify: Restart nginx
