---
- name: Install ansible semaphore
  hosts: semaphore.DOMAIN.TLD
  roles:
     - { role: selfhostx.ansible.baserole, tags: baserole }
     - geerlingguy.git
     - geerlingguy.pip
     # - { role: selfhostx.certbot }
     - { role: selfhostx.ansible.nginx_common, tags: nginx_common }
     - geerlingguy.mysql
     # - stefanux.mysqlbackup
     - { role: selfhostx.ansible.semaphore, tags: semaphore }

  vars_files:
     - my-vault.yml

  vars:
    semaphore_hostname: "semaphore.DOMAIN.TLD"

    # semaphore_version: "2.9.37"
    semaphore_default_user: admin
    semaphore_default_user_make_admin: true
    semaphore_default_user_name: "John Doe"
    # semaphore_default_user_password: "-> vault"
    semaphore_default_user_mail: "mail@DOMAIN.TLD"

    semaphore_db_dialect: mysql
    # semaphore_db_password: "-> vault"

    # semaphore_access_key_encryption: "-> vault"
    # semaphore_cookie_encryption: "-> vault"
    # semaphore_cookie_hash: "-> vault"

    semaphore_mysql_install: false

    semaphore_nginx_remove_default_config: true
    semaphore_nginx_use_nginx_common_snippet: true

    # letsencrypt:
    certbot_create_method: nginx
    certbot_certs:
      - domains:
        - "{{ semaphore_hostname }}"
    certbot_auto_renew_minute: 17
    certbot_auto_renew_hour: 3
    certbot_admin_email: "mail@DOMAIN.TLD"
    certbot_create_if_missing: true
    certbot_install_from_source: false
