---
# handlers file for mattermost

- name: Restart nginx
  ansible.builtin.service:
    name: nginx
    state: restarted

- name: Restart mattermost
  ansible.builtin.service:
    name: mattermost
    state: restarted
