---
galaxy_info:
  role_name: bacula
  author: selfhostx
  description: Manage bacula from ansible

  license: MIT

  min_ansible_version: 2.9

  platforms:
    - name: Debian
      versions:
        - buster
        - bullseye
        - stretch
    - name: Ubuntu
      versions:
        - focal
        - bionic
        - jammy

  galaxy_tags:
   - backup
   - bacula
   - server
   - system

dependencies: []
